set nocompatible
set encoding=utf-8

set formatoptions+=1    "Don't end lines with 1-letter words
set wrapscan
set linebreak
set number
set relativenumber

" avoid unnecessary backups
set nobackup
set noswapfile
set nowb

" change buffers without saving
set hidden

" persistent undo
set undofile
set undodir=~/.vim/undodir

set incsearch  " search incrementally
set hlsearch   " Highlight search results
set ignorecase
set smartcase  " Ignore case unless capital letter is entered

"===============================================================================
" 4.UI SETTINGS
"===============================================================================

set wildmenu
set wildmode=list:longest,full
set wildignore+=.hg,.git,.svn                    " Version control
set wildignore+=*.aux,*.out,*.toc                " LaTeX intermediate files
set wildignore+=*.jpg,*.bmp,*.gif,*.png,*.jpeg   " binary images
set wildignore+=*.o,*.oo,*.obj,*.exe,*.dll       " compiled object files
set wildignore+=*.spl                            " compiled spelling word lists
set wildignore+=*.sw?                            " Vim swap files
set wildignore+=*.pyc                            " Python byte code
set wildignore+=*.orig                           " Merge resolution files
set wildignore+=*.class                          " Java Class files
set wildignore+=$VIMRUNTIME/doc/*.txt            " Individual helpfiles
set wildignore+=$VIMRUNTIME/doc/*.tar.gz         " compressed helpfiles
" For the `**` meaning, do a `:h starstar-wildcard`
set wildignore+=**/doc/*.txt

set showcmd
set history=100
set cmdheight=2

" no redrawing when executing macros
set lazyredraw
set ttyfast

set showmatch
" add angular brackets to match with %
set matchpairs+=<:>

" override default split directions
set splitbelow
set splitright

"===============================================================================
" 5.KEY BINDINGS
"===============================================================================

set pastetoggle=<F6>

" interchange : and ;
nnoremap ; :
vnoremap ; :
nnoremap : ;
vnoremap : ;

" quit without saving
nnoremap Q :q!<cr>

" Natural movement in case of wrapped lines; NO skipping
nnoremap j gj
vnoremap j gj
nnoremap k gk
vnoremap k gk

" Easy jumping to (B)eginning and (E)nd of line
nnoremap B ^
nnoremap E g_
vnoremap B ^
vnoremap E g_

" Disable the arrow keys for good :)
inoremap <Up> <NOP>
inoremap <Down> <NOP>
inoremap <Right> <NOP>
inoremap <Left> <NOP>
nnoremap <Up> <NOP>
nnoremap <Down> <NOP>
nnoremap <Right> <NOP>
nnoremap <Left> <NOP>

" Handle splits the right way
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" search results appear in middle of buffer and blink
nnoremap n nzz
nnoremap N Nzz

" Enable resaving a file as root with sudo
cmap w!! w !sudo tee % >/dev/null

" change working dir to current file's dir
cmap cd. lcd %:p:h

" visual shifting dows not exit visual mode
vnoremap < <gv
vnoremap > >gv

" follow tradition of C & D
nnoremap Y y$

" use terminal style mappings in cmd mode
cnoremap <C-a> <home>
cnoremap <C-e> <end>

" Scroll a little faster
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>

" Mappings for jumping to next/prev in quickfix window
nnoremap ]q :cnext<cr>
nnoremap [q :cprev<cr>

"===============================================================================
" 6.INDENTATION
"===============================================================================

set autoindent
set expandtab
set smarttab

" Default python guided indentation
set tabstop=4
set softtabstop=4
set shiftwidth=4

" custom indentation for specific filetypes
augroup indentation
    autocmd!
    autocmd FileType html,css,javascript,javascript.jsx setlocal tabstop=2 shiftwidth=2 softtabstop=2
augroup END

"===============================================================================
" 7.STATUSLINE
"===============================================================================
set laststatus=2
set showtabline=2
" see buftabline config for statusline

"===============================================================================
" 8.DISPLAY
"===============================================================================

syntax enable
set t_Co=256
set background=dark
colorscheme flattened_dark
set scrolloff=5                           "Scroll when 12 lines from top or bottom
set cursorline                            "Horizontal highlighting of cursorline

let mapleader = "\<Space>"

" Edit my vimrc in a vert-split
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
" Source my vimrc in place
nnoremap <leader>sv :source $MYVIMRC<cr>

" Clear highlighting of searched text
nnoremap <leader>h :nohlsearch<cr>

" Toggle quickfix window
function! s:QuickfixToggle()
    for i in range(1, winnr('$'))
        let bnum = winbufnr(i)
        if getbufvar(bnum, '&buftype') == 'quickfix'
            cclose
            return
        endif
    endfor
    copen
endf

command! ToggleQuickfix call <SID>QuickfixToggle()
nnoremap <leader>q :ToggleQuickfix<cr>

augroup Entrypoint
    autocmd!
    " Enter vim at last edit location before closing
    autocmd BufReadPost *
                \ if line("'\"") > 0 && line("'\"") <= line("$") |
                \   exe "normal! g`\"" |
                \ endif
augroup END

set timeoutlen=1000
set ttimeoutlen=0

hi MatchParen cterm=none ctermbg=190 ctermfg=196
hi search cterm=bold ctermbg=3 ctermfg=0
hi incsearch cterm=bold ctermbg=72 ctermfg=0
hi Todo cterm=bold,underline ctermbg=none ctermfg=1

hi ExtraWhiteSpace ctermbg=41
augroup whitespace
    autocmd!
    autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
    autocmd InsertLeave * match ExtraWhitespace /\s\+$/
    autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
augroup END
