# configs directories
export XDG_CONFIG_HOME="$HOME/.config"
export DOTFILES="$HOME/dotfiles"

# env variable settings
export DEFAULT_USER=`whoami`
export TERM="xterm-256color"
export NVIM_TUI_ENABLE_TRUE_COLOR=1
export HISTSIZE=10000
export SAVEHIST=10000

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# for colorized man pages
export LESS_TERMCAP_mb=$'\e[0;33m'
export LESS_TERMCAP_md=$'\e[0;35m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[1;34;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[0;31m'

# extend path variable
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/sbin:$PATH"
export PATH="$HOME/bin/:$PATH"

CASE_SENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
ENABLE_CORRECTION="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
ZSH_DISABLE_COMPFIX="true"

# workstation specific aliases; not tracked by git
[ -f $HOME/.aliases.local ] && source $HOME/.aliases.local

# env variables for zsh setup
export ZSH="$HOME/.config/oh-my-zsh"
source $ZSH/custom/themes/thunder.zsh
source $ZSH/custom/aliases.zsh
source $ZSH/custom/plugins.zsh
source $ZSH/oh-my-zsh.sh

# FZF for fuzzy finding
if [ -f ~/.fzf.zsh ]; then
	source ~/.fzf.zsh
	export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden'
fi
